export { default as Main } from './Main/Main';
export { default as Home } from './Home';
export { default as EditProject } from './Project/EditProject';
export { default as CreateProject } from './Project/CreateProject';
export { default as Project } from './Project/Project';
export { default as User } from './User/User';
export { default as CreateUser } from './User/CreateUser';
export { default as EditUser } from './User/EditUser';
export { default as Login } from './Auth/Login';
